dist: trusty
language: java
jdk:
- oraclejdk8
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
  - secure: GySGZ4IewzcnvVlB2KTMT9x2qPOjbePojmTvNKASKeAeRINJqKBwao+qmzw/2fB/XUKGYNMnkDiQl6wNudqyC0HEgLCzqoZQDztnOL0wcIY0gCbpluAJYbEXzCTrMLa4T1gs1jA3onuqZYjlP+dM1mi+W4s4cK5rhRSMQKS9gPk=
  - secure: fseB3+AoImPAxINfE6yFsy51MT3u2mJ4yXTmvOmelqbK5ekX9dANyAHztmfIar3Ei/qBDbL57ctLY9CXyQtXDjAAcVeB6Xz0By5PXJ5joC5Bf5ZtkwcqEJI7BUDswWnFJb1Q/DP2KJR3XGwJr6QUAhIp4LVekKHCLJOPpHt7USo=

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE cloudfier;"  -U postgres
  - psql -c "CREATE USER cloudfier;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE cloudfier TO cloudfier;" -U postgres

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - stage: compile_and_test
      script: mvn clean install
    - stage: deploy
      script: mvn org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy --settings deploy.settings.xml -DdeployAtEnd=true -Dmaven.test.skip=true -f releng/com.abstratt.kirra.server.product
