language: java
jdk:
  - oraclejdk8
install: 
    - mvn clean install
before_script:
  - DATABASE=cloudfier
  - USERNAME=cloudfier
  - PASSWORD=
  - psql -d postgres -c "DROP DATABASE IF EXISTS ${DATABASE};"
  - psql -d postgres -c "DROP USER IF EXISTS ${USERNAME};"
  - psql -d postgres -c "CREATE USER ${USERNAME} WITH CREATEDB;"
  - psql -d postgres -c "ALTER USER ${USERNAME} PASSWORD '${PASSWORD}';"
  - psql -d postgres -c "CREATE DATABASE ${DATABASE} OWNER ${USERNAME};"
