package com.abstratt.kirra;


/**
 * Represents a property.
 */
public class Property extends DataElement {
	
	private boolean unique;

	private static final long serialVersionUID = 1;
	
	public Property() {
	}
	
	public boolean isUnique() {
		return unique;
	}
	
	public void setUnique(boolean unique) {
		this.unique = unique;
	}
	public boolean isAutoGenerated() {
		return isUnique() && !isInitializable() && !isEditable();
	}
}