<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="query"
    nsURI="http://abstratt.com/mdd/1.0.0/query" nsPrefix="query">
  <eClassifiers xsi:type="ecore:EClass" name="Query" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" Represents a query. "/>
    </eAnnotations>
    <eOperations name="getTargetType" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceType" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joins" ordered="false"
        upperBound="-1" eType="#//Join" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyReference" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableReference" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Variable"/>
  </eClassifiers>
</ecore:EPackage>
